Add some Equipment Icons
foundryvtt/pf2e pull request #10884
Opened 2023-10-23 20:47 UTC by InfamousSky

2023-10-23 21:13 UTC, stwlam commented on packs/equipment/bewitching-bloom-purple-iris.json
> +            "value": "<p>While dormant, this tattoo appears to be a simple flower bud, but when activated the flower swiftly blossoms, remaining that way until the next time you make your daily prepa
😮

2023-10-23 22:52 UTC, stwlam requested changes
Needs to use core icons where appropriate, and also a better frying pan

2023-10-24 15:43 UTC, TikaelSol commented on packs/equipment/bewitching-bloom-purple-iris.json
> +            "value": "<p>While dormant, this tattoo appears to be a simple flower bud, but when activated the flower swiftly blossoms, remaining that way until the next time you make your daily prepa
```suggestion
            "value": "<p>While dormant, this tattoo appears to be a simple flower bud, but when activated the flower swiftly blossoms, remaining that way until the next time you make your daily preparations. These blooms are colorful, elegant representations of purple iris flowers.</p>\n<p><strong>Activate</strong><span class=\"action-glyph\">2</span> envision</p>\n<p><strong>Frequency</strong> once per day</p>\n<hr />\n<p><strong>Effect</strong> Choose a willing ally you can see within 30 feet. Your ally takes on a regal bearing, exuding the presence of confident royalty. The bloom casts a 5th-level @UUID[Compendium.pf2e.spells-srd.Item.Command] spell (DC 28) selecting targets within range of the ally. Each target that fails the save must fall @UUID[Compendium.pf2e.conditionitems.Item.Prone] and pays homage to your ally.</p>"
```

It's emphasized by CSS now, no need for the tags. Post player core someone can run something to remove all the existing tags to save however much space in compendiums.

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/bewitching-bloom-white-poppy.json
> +            "value": "<p>While dormant, this tattoo appears to be a simple flower bud, but when activated the flower swiftly blossoms, remaining that way until the next time you make your daily prepa
```suggestion
            "value": "<p>While dormant, this tattoo appears to be a simple flower bud, but when activated the flower swiftly blossoms, remaining that way until the next time you make your daily preparations. These blooms are colorful, elegant representations of white poppy flowers.</p>\n<p><strong>Activate</strong><span class=\"action-glyph\">2</span> envision</p>\n<p><strong>Frequency</strong> once per day</p>\n<hr />\n<p><strong>Effect</strong> Choose a willing ally you can see within 30 feet. A sense of peace overwhelms the ally. The tattoo casts @UUID[Compendium.pf2e.spells-srd.Item.Calm] or @UUID[Compendium.pf2e.spells-srd.Item.Sanctuary] (your choice) on the ally. The spell affects only the ally and lasts only until the end of your next turn. Your ally need not be willing if under the control of another creature. However, the controlling creature can attempt a @Check[type:will|dc:20] save, disrupting your activation on a success.</p>"
```

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/wand-of-mental-purification-1st-level.json
> +            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</stro
```suggestion
            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</strong> once per day, plus overcharge</p>\n<hr />\n<p><strong>Effect</strong> You cast 1st-level <em>@UUID[Compendium.pf2e.spells-srd.Item.Soothe]</em>, and can attempt to counteract one mental effect on the same target. Treat the @UUID[Compendium.pf2e.spells-srd.Item.Soothe] spell's level as 1 higher for this counteract check.</p>\n<hr />\n<p><strong>Craft Requirements</strong> Supply a casting of <em>soothe</em> of the appropriate level.</p>"
```

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/wand-of-mental-purification-2nd-level.json
> +            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</stro
```suggestion
            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</strong> once per day, plus overcharge</p>\n<hr />\n<p><strong>Effect</strong> You cast 2nd-level <em>@UUID[Compendium.pf2e.spells-srd.Item.Soothe]</em>, and can attempt to counteract one mental effect on the same target. Treat the @UUID[Compendium.pf2e.spells-srd.Item.Soothe] spell's level as 1 higher for this counteract check.</p>\n<hr />\n<p><strong>Craft Requirements</strong> Supply a casting of <em>soothe</em> of the appropriate level.</p>"
```

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/wand-of-mental-purification-3rd-level.json
> +            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</stro
```suggestion
            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</strong> once per day, plus overcharge</p>\n<hr />\n<p><strong>Effect</strong> You cast 3rd-level <em>@UUID[Compendium.pf2e.spells-srd.Item.Soothe]</em>, and can attempt to counteract one mental effect on the same target. Treat the @UUID[Compendium.pf2e.spells-srd.Item.Soothe] spell's level as 1 higher for this counteract check.</p>\n<hr />\n<p><strong>Craft Requirements</strong> Supply a casting of <em>soothe</em> of the appropriate level.</p>"
```

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/wand-of-mental-purification-4th-level.json
> +            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</stro
```suggestion
            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</strong> once per day, plus overcharge</p>\n<hr />\n<p><strong>Effect</strong> You cast 4th-level <em>@UUID[Compendium.pf2e.spells-srd.Item.Soothe]</em>, and can attempt to counteract one mental effect on the same target. Treat the @UUID[Compendium.pf2e.spells-srd.Item.Soothe] spell's level as 1 higher for this counteract check.</p>\n<hr />\n<p><strong>Craft Requirements</strong> Supply a casting of <em>soothe</em> of the appropriate level.</p>"
```

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/wand-of-mental-purification-5th-level.json
> +            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</stro
```suggestion
            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</strong> once per day, plus overcharge</p>\n<hr />\n<p><strong>Effect</strong> You cast 5th-level <em>@UUID[Compendium.pf2e.spells-srd.Item.Soothe]</em>, and can attempt to counteract one mental effect on the same target. Treat the @UUID[Compendium.pf2e.spells-srd.Item.Soothe] spell's level as 1 higher for this counteract check.</p>\n<hr />\n<p><strong>Craft Requirements</strong> Supply a casting of <em>soothe</em> of the appropriate level.</p>"
```

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/wand-of-mental-purification-6th-level.json
> +            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</stro
```suggestion
            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</strong> once per day, plus overcharge</p>\n<hr />\n<p><strong>Effect</strong> You cast 6th-level <em>@UUID[Compendium.pf2e.spells-srd.Item.Soothe]</em>, and can attempt to counteract one mental effect on the same target. Treat the @UUID[Compendium.pf2e.spells-srd.Item.Soothe] spell's level as 1 higher for this counteract check.</p>\n<hr />\n<p><strong>Craft Requirements</strong> Supply a casting of <em>soothe</em> of the appropriate level.</p>"
```

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/wand-of-mental-purification-7th-level.json
> +            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</stro
```suggestion
            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</strong> once per day, plus overcharge</p>\n<hr />\n<p><strong>Effect</strong> You cast 7th-level <em>@UUID[Compendium.pf2e.spells-srd.Item.Soothe]</em>, and can attempt to counteract one mental effect on the same target. Treat the @UUID[Compendium.pf2e.spells-srd.Item.Soothe] spell's level as 1 higher for this counteract check.</p>\n<hr />\n<p><strong>Craft Requirements</strong> Supply a casting of <em>soothe</em> of the appropriate level.</p>"
```

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/wand-of-mental-purification-8th-level.json
> +            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</stro
```suggestion
            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</strong> once per day, plus overcharge</p>\n<hr />\n<p><strong>Effect</strong> You cast 8th-level <em>@UUID[Compendium.pf2e.spells-srd.Item.Soothe]</em>, and can attempt to counteract one mental effect on the same target. Treat the @UUID[Compendium.pf2e.spells-srd.Item.Soothe] spell's level as 1 higher for this counteract check.</p>\n<hr />\n<p><strong>Craft Requirements</strong> Supply a casting of <em>soothe</em> of the appropriate level.</p>"
```

2023-10-24 15:49 UTC, TikaelSol commented on packs/equipment/wand-of-mental-purification-9th-level.json
> +            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</stro
```suggestion
            "value": "<p>Red feathers hang from the handle of this ivory wand. Holding it brings a sense of gentle calm.</p>\n<p><strong>Activate</strong> Cast a Spell</p>\n<p><strong>Frequency</strong> once per day, plus overcharge</p>\n<hr />\n<p><strong>Effect</strong> You cast 9th-level <em>@UUID[Compendium.pf2e.spells-srd.Item.Soothe]</em>, and can attempt to counteract one mental effect on the same target. Treat the @UUID[Compendium.pf2e.spells-srd.Item.Soothe] spell's level as 1 higher for this counteract check.</p>\n<hr />\n<p><strong>Craft Requirements</strong> Supply a casting of <em>soothe</em> of the appropriate level.</p>"
```

2023-10-24 19:20 UTC, stwlam approved these changes

2023-10-25 16:34 UTC, merged