update instances of `/r` for `@Damage` for re-en.json
foundryvtt/pf2e pull request #15435
Opened 2024-07-14 05:27 UTC by ammalagonc

2024-07-14 06:59 UTC, j-bs reviewed
Found a few errors 👀

2024-07-14 06:59 UTC, j-bs commented on static/lang/re-en.json
> +                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals2*@Damage[4d4[persistent,piercing]] and @Damage[(4[splash])[poison]]{4 poison splash damage}. The bomb's splash area
```suggestion
                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals 2*@Damage[4d4[persistent,piercing]] and @Damage[(4[splash])[poison]]{4 poison splash damage}. The bomb's splash area is coated in vegetation, becoming difficult terrain for 1 minute.",
```

2024-07-14 06:59 UTC, j-bs commented on static/lang/re-en.json
> +                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[(1[splash])[bludgeoning]]1 bludgeoning splash damage}, Tiny or smaller targets are pushed 5 feet away from
```suggestion
                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[(1[splash])[bludgeoning]]{1 bludgeoning splash damage}, Tiny or smaller targets are pushed 5 feet away from you, and the target is knocked @UUID[Compendium.pf2e.conditionitems.Item.j91X7x0XSomq8d60]{Prone}.",
```

2024-07-14 06:59 UTC, j-bs commented on static/lang/re-en.json
> +                    "success": "<strong>Effect</strong> The bomb also deals @Damage[3d4[persistent,fire]] and @Damage[(3[splash])[fire]]3 fire splash damage}."
```suggestion
                    "success": "<strong>Effect</strong> The bomb also deals @Damage[3d4[persistent,fire]] and @Damage[(3[splash])[fire]]{3 fire splash damage}."
```

2024-07-14 06:59 UTC, j-bs commented on static/lang/re-en.json
> +                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[(2[splash])[mental]][mental]]]{2 mental splash damage} and the target must succeed at a @Check[type:flat|dc
```suggestion
                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[(2[splash])[mental]]{2 mental splash damage} and the target must succeed at a @Check[type:flat|dc:5] before taking actions with the concentrate trait, this lasts for 1 minute.",
```

2024-07-14 06:59 UTC, j-bs commented on static/lang/re-en.json
> +                        "TwentiethLevel": "The creature takes  @Damage[4d6[persistent,void]] damage. While the creature has this persistent damage, it's also @UUID[Compendium.pf2e.conditionitems.Item
```suggestion
                        "FourteenthLevel": "The creature takes @Damage[3d6[persistent,void]] damage. While the creature has this persistent damage, it's also @UUID[Compendium.pf2e.conditionitems.Item.e1XGnhKNSQIm5IXg]{Stupefied 1}.",
                        "TwentiethLevel": "The creature takes @Damage[4d6[persistent,void]] damage. While the creature has this persistent damage, it's also @UUID[Compendium.pf2e.conditionitems.Item.e1XGnhKNSQIm5IXg]{Stupefied 1}."
```

2024-07-14 06:59 UTC, j-bs commented on static/lang/re-en.json
> +                    "success": "<strong>Effect</strong> The bomb also deals  @Damage[1d4[persistent,piercing]] and @Damage[(1[splash])[poison]]{1 poison splash damage}. One square of the target creat
```suggestion
                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals 2*@Damage[1d4[persistent,piercing]] and @Damage[(1[splash])[poison]]{1 poison splash damage}. One square of the target creature's space is coated in vegetation, becoming difficult terrain for 1 round.",
                    "success": "<strong>Effect</strong> The bomb also deals @Damage[1d4[persistent,piercing]] and @Damage[(1[splash])[poison]]{1 poison splash damage}. One square of the target creature's space is coated in vegetation, becoming difficult terrain for 1 round."
```

2024-07-14 06:59 UTC, j-bs commented on static/lang/re-en.json
> +                    "success": "<strong>Effect</strong> The bomb also deals @Damage[(3[splash])[bludgeoning]]."
```suggestion
                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[(3[splash])[bludgeoning]]{3 bludgeoning splash damage}. The target is @UUID[Compendium.pf2e.conditionitems.Item.TkIyaNPgTZFBCCuh]{Dazzled} until the start of your next turn.",
                    "success": "<strong>Effect</strong> The bomb also deals @Damage[(3[splash])[bludgeoning]]{3 bludgeoning splash damage}."
```

2024-07-14 08:15 UTC, Cuingamehtar commented
A lot of the changes break the formulas here. Where there is doubling in the formula, it's outright removed or has to be done manually now (all of persistent damage strings and bombs).
Nagaji Venom Spit loses its persistent damage.

It's persist**e**nt, not persist**a**nt in damage labels. And if you are writing custom label for persistent damage link, it will automatically fill "n persistent element".

Also, a lot of those are not used in the current version. I imagine those are still there for legacy reasons, or for translations, which won't be affected by these changes.

2024-07-14 13:30 UTC, ammalagonc commented
Thanks for catching those typos, @j-bs. Please check again when you get a moment :)

2024-07-14 13:53 UTC, ammalagonc commented
@Cuingamehtar - I fixed the spelling on persistent. 

I will check later to see what the best approach is for doubling damage using `@Damage`. I was going off an existing example, but apparently, that doesn't work.

2024-07-14 14:10 UTC, Cuingamehtar commented
@ammalagonc Use brackets. @Damage[(2*2d4)[persistent,fire]] works.

2024-07-14 15:41 UTC, ammalagonc commented
Made corrections to the instances of critical damage (2*) in the file.

Please check when you get a moment.

Thanks again @Cuingamehtar and @j-bs for your reviews and making sure this is up to par :)

2024-07-14 15:49 UTC, Cuingamehtar requested changes
Please be more attentive to the formulas and damage types.

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[3d6[persistent,acid]]and @Damage[(3[splash])[acid]]{3 acid splash damage}.",
```suggestion
                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[3d6[persistent,acid]] and @Damage[(3[splash])[acid]]{3 acid splash damage}.",
```

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "criticalSuccess": "@Damage[(2*(2d6+4))[persistent,acid]]",
```suggestion
                "criticalSuccess": "@Damage[(2*2d6+4)[persistent,acid]]",
```
This +4 is already doubled.

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "criticalSuccess": "@Damage[(2*1d10)[bleed]]",
```suggestion
                "criticalSuccess": "@Damage[(2*2d10)[bleed]]",
```

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "criticalSuccess": "@Damage[(2*1d12)[bleed]]",
```suggestion
                "criticalSuccess": "@Damage[(2*2d12)[bleed]]",
```

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "success": "@Damage[1d12[bleed]]"
```suggestion
                "success": "@Damage[2d12[bleed]]"
```

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "success": "@Damage[1d10[bleed]]"
```suggestion
                "success": "@Damage[2d10[bleed]]"
```

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "criticalSuccess": "@Damage[(2*1d12)[persistent,fire]]",
```suggestion
                "criticalSuccess": "@Damage[(2*1d12)[persistent,force]]",
```

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "success": "@Damage[1d12[persistent,fire]]"
```suggestion
                "success": "@Damage[1d12[persistent,force]]"
```

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "criticalSuccess": "@Damage[(2*2d12)[persistent,fire]]",
```suggestion
                "criticalSuccess": "@Damage[(2*2d12)[persistent,force]]",
```

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "success": "@Damage[2d12[persistent,fire]]"
```suggestion
                "success": "@Damage[2d12[persistent,force]]"
```

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                "criticalSuccess": "@Damage[(2*(2d8+16))[persistent,piercing]]",
```suggestion
                "criticalSuccess": "@Damage[(2*2d8+16)[persistent,piercing]]",
```
+16 is already doubled

2024-07-14 15:49 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                    "CriticalNote": "The target takes @Damage[(1+@weapon.system.runes.striking)[poison]]{persistent poison damage} equal to the number of weapon damage dice",
```suggestion
                    "CriticalNote": "The target takes @Damage[(1+@weapon.system.runes.striking)[persistent,poison]]{persistent poison damage} equal to the number of weapon damage dice",
```

2024-07-14 16:09 UTC, ammalagonc commented
@Cuingamehtar - Changes made.

Please check when you get a moment. Thanks again for all you do.

2024-07-14 16:18 UTC, Cuingamehtar requested changes
A couple of mistakes I've missed on previous review.

The rest seems fine.

2024-07-14 16:18 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                    "success": "<strong>Effect</strong> The bomb also deals @Damage[(5[splash])[mental]]{3 mental splash damage} and the target is @UUID[Compendium.pf2e.conditionitems.Item.TBSHQspnbc
```suggestion
                    "success": "<strong>Effect</strong> The bomb also deals @Damage[(3[splash])[mental]]{3 mental splash damage} and the target is @UUID[Compendium.pf2e.conditionitems.Item.TBSHQspnbcqxsmjL]{Frightened 1} (@UUID[Compendium.pf2e.conditionitems.Item.TBSHQspnbcqxsmjL]{Frightened 2} on a critical)."
```

2024-07-14 16:18 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[3d6[persistent,acid]] and @Damage[(3[splash])[acid]]{3 acid splash damage}.",
```suggestion
                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[(2*3d6)[persistent,acid]] and @Damage[(3[splash])[acid]]{3 acid splash damage}.",
```

2024-07-14 16:18 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                    "Note": "When you critically succeed at a seedpod Strike, vines twist and stab your foe, dealing @Damage[1d4[persistent,piercing]]{1d4 persistent piercing}"
```suggestion
                    "Note": "When you critically succeed at a seedpod Strike, vines twist and stab your foe, dealing @Damage[1d4[persistent,piercing]]{1d4 persistent piercing damage}."
```

2024-07-14 16:18 UTC, Cuingamehtar commented on static/lang/re-en.json
> +                    "Note": "As long as you are suffering persistent fire damage, all your melee attacks against adjacent creatures deal an additional @Damage[1[fire]]{1 Fire Damage} per weapon damag
```suggestion
                    "Note": "As long as you are suffering persistent fire damage, all your melee attacks against adjacent creatures deal an additional @Damage[1[fire]]{1 fire damage} per weapon damage die."
```

2024-07-15 08:51 UTC, j-bs commented on static/lang/re-en.json
> +                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[2[bleed]] and @Damage[(2[splash])[slashing]]{2 slashing splash damage}.",
```suggestion
                    "criticalSuccess": "<strong>Effect</strong> The bomb also deals @Damage[(2*2)[bleed]] and @Damage[(2[splash])[slashing]]{2 slashing splash damage}.",
```
Spotted another cheeky typo on a crit 2x entry.

Looks like the last one.

2024-07-16 04:59 UTC, TikaelSol commented on static/lang/re-en.json
> +                    "success": "<strong>Effect</strong> The bomb also deals @Damage[(3d6[persistent,acid]]{3d6 persistent acid} and @Damage[(3[splash])[acid]]{3 acid splash damage}."
```suggestion
                    "success": "<strong>Effect</strong> The bomb also deals @Damage[3d6[persistent,acid]] and @Damage[(3[splash])[acid]]{3 acid splash damage}."
```

2024-07-16 04:59 UTC, TikaelSol commented on static/lang/re-en.json
> +                    "success": "<strong>Effect</strong> The bomb also deals @Damage[1d6[persistent,acid]]{1d6 persistent acid} and @Damage[(1[splash])[acid]]{1 acid splash damage}."
```suggestion
                    "success": "<strong>Effect</strong> The bomb also deals @Damage[1d6[persistent,acid]] and @Damage[(1[splash])[acid]]{1 acid splash damage}."
```

2024-07-16 04:59 UTC, TikaelSol commented on static/lang/re-en.json
> +                "CeustodaemonDamageNote": "Any successful jaws or claw Strike deals an additional @Damage[1d6[untyped]]{1d6 damage}, and you take the same amount of damage"
```suggestion
                "CeustodaemonDamageNote": "Any successful jaws or claw Strike deals an additional @Damage[1d6[untyped]] damage, and you take the same amount of damage"
```

2024-07-16 04:59 UTC, TikaelSol commented on static/lang/re-en.json
> +                "SingleAttackEffect": "The attack deals @Damage[1d12[untyped]]{1d12 damage} on a failure.",
```suggestion
                "SingleAttackEffect": "The attack deals @Damage[1d12[untyped]] damage on a failure.",
```

2024-07-16 04:59 UTC, TikaelSol commented on static/lang/re-en.json
> +                    "Note": "When you successfully Demoralize a foe, that foe takes @Damage[1d4[mental]]{1d4 mental damage} at the start of each of its turns as long as it remains Frightened and cont
```suggestion
                    "Note": "When you successfully Demoralize a foe, that foe takes @Damage[(ternary(gte(@actor.system.skills.intimidation.rank,4),3,ternary(gte(@actor.system.skills.intimidation.rank,3),2,1))d4)[mental]]{1d4 mental damage} at the start of each of its turns as long as it remains Frightened and continues to engage in combat with you. If you have master proficiency in Intimidation, the damage increases to 2d4, and if you have legendary proficiency, the damage increases to 3d4."
```

2024-07-16 04:59 UTC, TikaelSol commented on static/lang/re-en.json
> +                    "Note": "When you critically succeed at a seedpod Strike, vines twist and stab your foe, dealing @Damage[1d4[persistent,piercing]]{1d4 persistent piercing damage}."
```suggestion
                    "Note": "When you critically succeed at a seedpod Strike, vines twist and stab your foe, dealing @Damage[1d4[persistent,piercing]] damage."
```

2024-07-16 04:59 UTC, TikaelSol commented on static/lang/re-en.json
> +                    "CriticalNote": "The target takes @Damage[(1+@weapon.system.runes.striking)[persistent,poison]]{persistent poison damage} equal to the number of weapon damage dice",
```suggestion
                    "CriticalNote": "The target takes @Damage[(@weapon.system.damage.dice)[persistent,poison]]{persistent poison damage} equal to the number of weapon damage dice",
```

2024-07-16 05:03 UTC, merged