Add `remaster` table class to `_globals.css`
foundryvtt/pf2e pull request #16750
Opened 2024-10-04 00:05 UTC by ammalagonc

2024-10-06 23:22 UTC, stwlam commented on src/styles/_globals.scss
> +        }
Remove anything not theme-specific

2024-10-06 23:39 UTC, ammalagonc commented on src/styles/_globals.scss
> +        }
Check when you get a moment.

Thanks!

2024-10-07 02:11 UTC, stwlam commented on src/styles/_globals.scss
> +            padding: 0.5rem 0.25rem;
Use space variables (e.g.,  `padding: var(--space-8) var(--space-4);`)

2024-10-14 02:45 UTC, stwlam requested changes

2024-10-14 02:45 UTC, stwlam commented on src/styles/_globals.scss
> +        }
```suggestion
```

2024-10-14 02:45 UTC, stwlam commented on src/styles/_globals.scss
> +            font-weight: bold;
```suggestion
```
Remember that you're just overriding the thing syou want to change.

2024-10-14 02:45 UTC, stwlam commented on src/styles/_globals.scss
> +
```suggestion
```

2024-10-15 22:03 UTC, stwlam commented on src/styles/_globals.scss
> +            padding: var(--space-8) var(--space-4);
omg

2024-10-15 22:04 UTC, stwlam commented on src/styles/_globals.scss
> +            padding: var(--space-8) var(--space-4);
```suggestion
```

2024-10-15 22:04 UTC, stwlam commented on src/styles/_globals.scss
> +            text-align: center;
```suggestion
            border-border: var(--color-border-light-tertiary);
```

2024-10-15 22:05 UTC, stwlam approved these changes

2024-10-16 03:53 UTC, merged