Add third free ability boost to Amnesiac and Discarded Duplicate backgrounds
foundryvtt/pf2e pull request #2422
Opened 2022-06-11 10:13 UTC by kolontaev

Fix https://github.com/foundryvtt/pf2e/issues/2324

2022-06-12 15:47 UTC, SpartanCPA approved these changes
Data is approved. @stwlam for the code additions

2022-06-13 02:31 UTC, stwlam commented on src/module/migration/migrations/759-add-third-free-ability-boost.ts
> +}
just make this a private getter

2022-06-16 05:22 UTC, stwlam requested changes

2022-06-16 05:22 UTC, stwlam commented on src/module/migration/migrations/759-add-third-free-ability-boost.ts
> +        const slug = itemSource.data.slug ?? sluggify(itemSource.name);
We don't want to include custom items that the user happened to name "Amnesiac"

2022-06-16 05:22 UTC, stwlam commented on src/module/migration/migrations/759-add-third-free-ability-boost.ts
> +        if (!(slug === "amnesiac" || slug === "discarded-duplicate")) return;
```suggestion
        if (!["amnesiac", "discarded-duplicate"].includes(slug)) return;
```

2022-06-25 09:05 UTC, CarlosFdez commented
I think for this to work well, we'll also need UI changes that will allow for a dynamic number of ability boosts

2022-06-27 04:22 UTC, TMunsie commented
@fryguy1013 Does #2731 supercede and close this PR?

2022-06-27 07:59 UTC, fryguy1013 commented
Looks like it. Closing.

2022-06-27 07:59 UTC, closed without merging