add Fistful of flowers items, PCs and NPCs
foundryvtt/pf2e pull request #2744
Opened 2022-06-27 20:17 UTC by TMunsie

2022-06-30 18:37 UTC, TikaelSol commented
I can never remember if we get to add these before the PDF is actually out.

2022-06-30 19:13 UTC, TMunsie commented
> I can never remember if we get to add these before the PDF is actually out.



> I can never remember if we get to add these before the PDF is actually out.

It is being run at conventions, which is our "new bar". I'll be adding a bunch of PFS stuff pre-GenCon for the same reason :) The Free RPG dayu adventure is allowed to be run online/using Foundry IF the players and GM could have run it at the same FLGS. Since Foundry can be run offline this fits within our new, friendly-with-Paizo rules since no lore/adventure content is going in.

2022-06-30 22:16 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/meliosas-leshy-golden-bamboo.json
> +                "custom": "speak with plants (same type as leshy)",
```suggestion
                "custom": "Speak with Plants (Golden Bamboo Only)",
```

2022-06-30 22:18 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/meliosas-leshy-golden-bamboo.json
> +                },
```suggestion
                },
                "deathNote": true,
```

2022-06-30 22:25 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/meliosas-leshy.json
> +                    "value": "<p>When a leshy dies, a burst of primal energy explodes from its body, restoring [[/r 2d8 # hit points]]{2d8 Hit Points} to each plant creature within a @Template[type:e
```suggestion
                    "value": "<p>When a leshy dies, a burst of primal energy explodes from its body, restoring [[/r {2d8}[healing]]]{2d8 Hit Points} to each plant creature within a @Template[type:emanation|distance:30]. This area is filled with plants of the same type as the leshy, becoming difficult terrain. If the terrain isn't a viable environment for these plants, they wither after 24 hours.</p>"
```

2022-06-30 22:26 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/meliosas-leshy.json
> +                },
```suggestion
                },
                "deathNote": true,
```

2022-06-30 22:27 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/meliosas-leshy-minkaian-honeysuckle-leshy.json
> +                "custom": "speak with plants (same type as leshy)",
```suggestion
                "custom": "Speak with Plants (Minkaian Honeysuckle Only)",
```

2022-06-30 22:27 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/meliosas-leshy-minkaian-honeysuckle-leshy.json
> +                },
```suggestion
                },
                "deathNote": true,
```

2022-06-30 22:33 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/meliosas-leshy-wisteria-leshy.json
> +                },
```suggestion
                },
                "deathNote": true,
```

2022-06-30 22:33 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/meliosas-leshy-wisteria-leshy.json
> +                    "value": "<p>When a leshy dies, a burst of primal energy explodes from its body, restoring [[/r 2d8 # hit points]]{2d8 Hit Points} to each plant creature within a @Template[type:e
```suggestion
                    "value": "<p>When a leshy dies, a burst of primal energy explodes from its body, restoring [[/r {2d8}[healing]]]{2d8 Hit Points} to each plant creature within a @Template[type:emanation|distance:30]. This area is filled with plants of the same type as the leshy, becoming difficult terrain. If the terrain isn't a viable environment for these plants, they wither after 24 hours.</p>"
```

2022-06-30 23:01 UTC, SpartanCPA requested changes

2022-06-30 23:01 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/scented-candle-homunculus.json
> +                    "value": "<p>@Compendium[pf2e.bestiary-ability-glossary-srd.Aura]{Aura} 5 feet.</p>\n<p>The scented candle homunculus's fragrance of lavender is overwhelmingly intense. Any creatu
```suggestion
                    "value": "<p>@Template[type:emanation|distance:5]{5 feet} @Compendium[pf2e.bestiary-ability-glossary-srd.Aura]{Aura}</p>\n<p>The scented candle homunculus's fragrance of lavender is overwhelmingly intense. Any creature other than the homunculus's master who enters the aura must attempt a @Check[type:fortitude|dc:15] save.</p>\n<hr />\n<p><strong>Critical Success</strong> The creature is temporarily immune to the homunculus's aura for 24 hours.</p>\n<p><strong>Success</strong> The creature is unaffected.</p>\n<p><strong>Failure</strong> The creature is @Compendium[pf2e.conditionitems.Sickened]{Sickened 1}.</p>\n<p><strong>Critical Failure</strong> The creature is @Compendium[pf2e.conditionitems.Stupefied]{Stupefied 1} for 1 round and sickened 1.</p>"
```

2022-06-30 23:01 UTC, SpartanCPA commented on packs/data/one-shot-bestiary.db/scented-candle-homunculus.json
> +                    "value": "<p>A scented candle homunculus who is adjacent to the large wax cauldron can dunk itself in wax, [[/r {2d6} # hit points]]{healing 2d6 damage}.</p>"
```suggestion
                    "value": "<p>A scented candle homunculus who is adjacent to the large wax cauldron can dunk itself in wax, [[/r {2d6}[healing]]]{healing 2d6 damage}.</p>"
```

2022-07-01 00:55 UTC, SpartanCPA approved these changes

2022-07-01 00:59 UTC, merged