Crafting Entry Migration
foundryvtt/pf2e pull request #3548
Opened 2022-08-16 19:31 UTC by ebuckle

Finish work started in previous PR to migrate old crafting entries and related REs.

2022-08-17 17:56 UTC, stwlam requested changes

2022-08-17 17:56 UTC, stwlam commented on src/module/migration/migrations/773-unpersist-crafting-entries-and-add-predicate.ts
> +        itemSource.system.rules ??= [];
```suggestion
```
Were this actually a problem, we'd have a way more serious mess to clean up

2022-08-17 17:56 UTC, stwlam commented on src/module/migration/migrations/773-unpersist-crafting-entries-and-add-predicate.ts
> +                Array.isArray(rule["requiredTraits"])
```suggestion
                rule.key === "CraftingEntry" && Array.isArray(rule.requiredTraits)
```

2022-08-17 17:56 UTC, stwlam commented on src/module/migration/migrations/773-unpersist-crafting-entries-and-add-predicate.ts
> +                    });
A map that requires nothing is a for-loop.

2022-08-17 17:56 UTC, stwlam commented on src/module/migration/migrations/773-unpersist-crafting-entries-and-add-predicate.ts
> +        });
Change to for-loop

2022-08-17 17:58 UTC, stwlam requested changes
Fix PR title to be in imperative mood.

2022-08-17 22:12 UTC, ebuckle commented
Changes in

2022-08-17 22:16 UTC, stwlam commented
Does this change anything in compendium JSON?

2022-08-19 17:20 UTC, stwlam approved these changes

2022-08-19 17:20 UTC, merged