Unpersist existing Crafting Entry REs
foundryvtt/pf2e pull request #3573
Opened 2022-08-19 20:12 UTC by ebuckle

Now storing entry data on the parent item RE rather than the actor.

2022-08-22 16:19 UTC, stwlam commented
Conflicts! Also, please run migration.

2022-08-22 19:45 UTC, ebuckle commented
Merged and run

2022-08-23 05:06 UTC, stwlam commented on src/module/actor/character/crafting/entry.ts
> +        this.parentItem = data.parentItem || {};
The types doesn't blow up here only because `data.parentItem` is not-nullish. Why the `|| {}`?

2022-08-23 05:06 UTC, stwlam commented on src/module/actor/character/crafting/entry.ts
> +                isSignatureItem: !!formula.isSignatureItem,
Same question as above

2022-08-23 05:06 UTC, stwlam commented on src/module/actor/character/crafting/entry.ts
> +            .reduce((sum, current) => sum + (current.quantity || 1), 0);
Same

2022-08-23 20:51 UTC, stwlam requested changes
Bump `LASTED_SCHEMA_VERSION`

2022-08-23 21:08 UTC, ebuckle commented
Ah woops, caught it in the migration, forgot it there

2022-08-23 21:23 UTC, stwlam approved these changes

2022-08-23 21:23 UTC, merged