Expose self and target's ID as rollOptions
foundryvtt/pf2e pull request #4657
Opened 2022-10-31 22:18 UTC by Cerapter

Assuming a single target for a roll, this PR will make it so that `self:id:XYZ` and `target:id:ABC` are now available rollOptions to use.

`self:id` is available for targetless rolls as well.

2022-10-31 22:31 UTC, stwlam commented
could have sworn we already had this ...

2022-10-31 22:31 UTC, Cerapter commented on src/module/actor/creature/index.ts
> +        this.rollOptions.all[`self:id:${this.id}`] = true;
This _could_ be moved to `ActorPF2e`, as it doesn't cause any problems, but that doesn't bring any new features with it.
Hazards and loot boxes won't have their ID grabbed for `target:id`, and the hazards' rolls are uninspectable due to an error anyways. Loot boxes don't usually roll.

2022-10-31 22:32 UTC, stwlam requested changes
Set it in `ActorPF2e#prepareBaseData` right after the flag is initially added.

2022-10-31 22:32 UTC, Cerapter commented
> could have sworn we already had this ...

If this is not sarcasm, then not gonna lie, same. I thought it was already a feature. But the closest I can see is weapon IDs.

2022-10-31 22:41 UTC, CarlosFdez commented
Yeah checking the roll inspector, its not set. There's no self:id:blah field

2022-10-31 22:43 UTC, stwlam commented on src/module/actor/base.ts
> +
Check that they have an ID (temporary actors won't necessarily).

2022-10-31 23:40 UTC, stwlam approved these changes

2022-10-31 23:42 UTC, stwlam commented
Hm, only misgiving here is that synthetic actors will share IDs, which will lead to unwanted results if not anticipated.

2022-10-31 23:46 UTC, Cerapter commented
Can anything be done about that?

2022-10-31 23:47 UTC, stwlam commented
Not until V11 when synthetic actors (hopefully) go away for good.

2022-11-11 08:05 UTC, stwlam commented
I think we're going to have to wait until V11 for this sort of thing to be usable.

2022-11-11 08:05 UTC, closed without merging

2022-11-11 19:14 UTC, Cerapter commented
No worries. Your PR #4659 already seemingly does what I wanted to do with this one, so I don't need this too bad. It might have some other uses, but marking is basically what I wanted to get outta it.