Review EC book 6 NPCs (part 1 of 6)
foundryvtt/pf2e pull request #5916
Opened 2023-01-26 00:03 UTC by roxim5

2023-01-28 05:35 UTC, SpartanCPA commented on packs/data/extinction-curse-bestiary.db/convergent-giant-eagle.json
>                          "label": "An ally with Convergent Tactics is within reach of the target",
Should be @Localized

2023-01-28 23:40 UTC, roxim5 commented on packs/data/extinction-curse-bestiary.db/convergent-giant-eagle.json
>                          "label": "An ally with Convergent Tactics is within reach of the target",
Localized

2023-01-29 01:41 UTC, SpartanCPA requested changes

2023-01-29 01:41 UTC, SpartanCPA commented on packs/data/extinction-curse-bestiary.db/saurian-warmonger.json
> +                    "value": "<p>The saurian warmonger bellows, evoking the power of the primordial world.</p>\n<p>Non-dinosaur creatures within @Template[type:emanation|distance:30]{30 feet} take [[
```suggestion
                    "value": "<p>The saurian warmonger bellows, evoking the power of the primordial world.</p>\n<p>Non-dinosaur creatures within @Template[type:emanation|distance:30]{30 feet} take [[/r 10d6[sonic]]] damage (@Check[type:fortitude|dc:34|basic:true] save). On a failed save, a creature is also @UUID[Compendium.pf2e.conditionitems.Slowed]{Slowed 2} for 1 round (@UUID[Compendium.pf2e.conditionitems.Stunned]{Stunned} [[/r 1d4 #Stunned Value]]{1d4} on a critical failure).</p>\n<p>The saurian can't use Boneshaking Roar again for [[/br 1d4 #Boneshaking Roar Recharge]]{1d4 rounds}.</p>"
```

2023-01-29 01:41 UTC, SpartanCPA commented on packs/data/extinction-curse-bestiary.db/saurian-warmonger.json
>              "name": "+1 Striking Mancatcher",
Why did you use a Scimitar as the base item for this?

2023-01-29 01:41 UTC, SpartanCPA commented on packs/data/extinction-curse-bestiary.db/saurian-warmonger.json
> +                        "sweep"
Where do these come from? The traits aren't listed on the attack.

2023-01-29 01:41 UTC, SpartanCPA commented on packs/data/extinction-curse-bestiary.db/saurian-warmonger.json
> +            },
Should be removed as a Mancatcher isn't a Scimitar

2023-01-29 01:41 UTC, SpartanCPA commented on packs/data/extinction-curse-bestiary.db/saurian-worldwatcher.json
> +                    "value": "<p>The saurian warmonger bellows, evoking the power of the primordial world.</p>\n<p>Non-dinosaur creatures within @Template[type:emanation|distance:30]{30 feet} take [[
```suggestion
                    "value": "<p>The saurian worldwatcher bellows, evoking the power of the primordial world.</p>\n<p>Non-dinosaur creatures within @Template[type:emanation|distance:30]{30 feet} take [[/r 10d6[sonic]]] damage (@Check[type:fortitude|dc:38|basic:true] save). On a failed save, a creature is also @UUID[Compendium.pf2e.conditionitems.Slowed]{Slowed 2} for 1 round (@UUID[Compendium.pf2e.conditionitems.Stunned]{Stunned} [[/r 1d4 #Stunned Value]]{1d4} on a critical failure).</p>\n<p>The saurian can't use Boneshaking Roar again for [[/br 1d4 #Boneshaking Roar Cooldown]]{1d4 rounds}.</p>"
```

2023-01-29 02:07 UTC, SpartanCPA commented
MIght as well localize the convergent tactics for Kendley Nathrael as well in this PR. Will require a rebase to do so.

2023-01-31 13:27 UTC, SpartanCPA approved these changes

2023-01-31 13:27 UTC, merged