Begin automating deviant abilities
foundryvtt/pf2e pull request #5954
Opened 2023-01-27 06:17 UTC by TikaelSol

Debating between this easy implementation vs something more complicated like automaton enhancements. I'm leaning toward this since we are unlikely to get more deviant feats and time is limited for me. It can always be switched out later and it would require a migration to do the more complicated thing anyways.

2023-01-29 02:10 UTC, TikaelSol commented
Consume energy's effect will need a change to ChoiceSet to allow for choosing any strike. We need a way to handle the backlash tracking as well.

2023-01-30 04:23 UTC, simonward requested changes

2023-01-30 04:23 UTC, simonward commented on packs/data/classfeatures.db/strained-metabolism.json
> +            "value": "<p>Your body's overclocked physiology requires larger-than- usual amounts of nourishment, leaving you weakened when it kicks in mid-combat.</p>\n<p><strong>Mild Backlash</strong
Extra space after hyphen "larger-than- usual",

2023-01-30 04:23 UTC, simonward commented on packs/data/classfeatures.db/wraith-deviant-classification.json
> +    "name": "Wraith  Deviant Classification",
Extra space after Wraith.

2023-01-30 04:23 UTC, simonward commented on packs/data/feat-effects.db/effect-consume-energy-augment-strike.json
> +            "value": "<p>Strikes with the chosen weapon or unarmed attack deal an additional 1d6 damage of a type matching the energy you consumed</p>"
Missing period.

2023-01-30 04:23 UTC, simonward commented on packs/data/feats.db/distant-wandering.json
> +                "uuid": "Compendium.pf2e.classfeatures.Wraith  Deviant Classification"
Extra space in this and other references.

2023-02-02 04:08 UTC, merged