Add tint and alpha overrides to TokenImage
foundryvtt/pf2e pull request #7469
Opened 2023-04-19 21:33 UTC by TikaelSol

Before I fight typescript to resolve the errors is this something we'd be fine with adding in? It will help quite a bit with a third party thing I am working on and it's kind of a neat thing to be able to manage the tint/opacity of a token with a rule element.

2023-04-19 21:36 UTC, stwlam commented
I don't mind, but I do predict a casualty in this fight.

2023-04-19 21:40 UTC, TikaelSol commented
What issue you seeing on the horizon?

2023-04-19 21:41 UTC, stwlam commented
A second round of type errors after you resolve the initial ones.

2023-04-20 00:37 UTC, stwlam requested changes

2023-04-20 00:37 UTC, stwlam commented on src/module/rules/synthetics.ts
> +            | { src: VideoFilePath; tint: `#${string}` };
```suggestion
            | { src: VideoFilePath; tint?: HexColorField }
            | { src: VideoFilePath; tint?: HexColorField; scaleX: number; scaleY: number; };
```

2023-04-20 00:37 UTC, stwlam commented on src/module/scene/token-document/document.ts
>          }
```suggestion
        this.alpha = tokenOverrides.alpha ?? this.alpha;
```

2023-04-20 00:37 UTC, stwlam commented on src/module/scene/token-document/document.ts
> +            }
```suggestion
            this.texture.tint = tokenOverrides.texture.tint ?? this.texture.tint;
```

2023-04-20 00:37 UTC, stwlam commented on src/module/rules/rule-element/token-image.ts
> +        if (this.alpha) {
```suggestion
        if (typeof this.alpha === "number") {
```

2023-04-20 01:27 UTC, stwlam commented on src/module/rules/rule-element/token-image.ts
> +        const texture: { src: VideoFilePath; scaleX?: number; scaleY?: number; tint?: string } = { src };
```suggestion
        const texture: { src: VideoFilePath; scaleX?: number; scaleY?: number; tint?: HexColorString } = { src };
```

2023-04-20 01:27 UTC, stwlam commented on src/module/rules/rule-element/token-image.ts
> +    tint?: string;
```suggestion
    tint?: HexColorString;
```

2023-04-20 01:27 UTC, stwlam commented on src/module/rules/rule-element/token-image.ts
> +            this.tint = data.tint;
```suggestion
            this.tint = new Color(data.tint).toString();
```

2023-04-20 01:31 UTC, stwlam approved these changes

2023-04-20 01:33 UTC, merged